const P1Q={
"Art":["Do you like art?","Did you learn art when you were a child?","Do you often visit art galleries or exhibitions?"],
"Clothing":["What kind of clothes do you usually wear?","Do you enjoy buying clothes?","Have your clothing preferences changed over time?"],
"Singing":["Do you like singing?","When do you usually sing?","Did you sing a lot when you were a child?"],
"Headphone":["Do you often use headphones?","When do you usually wear headphones?","Do you think you use headphones too much?"],
"Telling Jokes":["Do you like telling jokes?","Who do you usually tell jokes to?","Are you good at remembering jokes?"],
"Mirrors":["Do you often look at yourself in a mirror?","Do you have many mirrors at home?","Have you ever bought a mirror?"],
"Science":["Did you enjoy science at school?","Is science useful in everyday life?","Would you like to learn more about science?"],
"Outer space and stars":["Are you interested in outer space and stars?","Did you learn about space at school?","Would you like to travel into space one day?"],
"Cars":["Do you often travel by car?","Do you think cars are important in your daily life?","Would you like to own a different car in the future?"],
"Parks":["Do you often go to parks?","What do you usually do in a park?","Are there enough parks where you live?"],
"Feeling bored":["Do you often feel bored?","What do you usually do when you feel bored?","Did you feel bored more often when you were younger?"],
"Shopping":["Do you enjoy shopping?","What do you usually shop for?","Do you prefer shopping online or in stores?"],
"Watch":["Do you usually wear a watch?","When did you first start wearing a watch?","Do you think watches are still useful now?"],
"Websites":["What kinds of websites do you use most often?","Is there a website you use every day?","Do you think you spend too much time on websites?"],
"Tidiness":["Are you a tidy person?","Do you keep your room tidy?","Were you tidier when you were a child?"],
"Music":["What kind of music do you like?","When do you usually listen to music?","Has your taste in music changed?"],
"Social media":["Do you use social media every day?","What do you usually use social media for?","Do you think you spend too much time on it?"],
"Teachers":["Do you remember a teacher you really liked?","What makes someone a good teacher?","Would you like to be a teacher?"],
"Daily routine":["Do you usually follow the same daily routine?","Which part of your daily routine do you enjoy most?","Would you like to change anything about your routine?"],
"Life stages":["Which stage of life do you think is the most interesting?","Do you think people's priorities change as they get older?","What did you enjoy most about being a child?"],
"View":["Is there a good view from your home?","What kind of view do you enjoy?","Do you ever take photos of beautiful views?"],
"Scenery":["What kind of natural scenery do you like?","Is there beautiful scenery near where you live?","Do you prefer city scenery or natural scenery?"],
"Childhood activities":["What did you enjoy doing as a child?","Did you usually play indoors or outdoors?","Are children's activities different today?"],
"Building":["What kind of buildings do you like?","Is there a building in your city that you find interesting?","Do you prefer old buildings or modern ones?"],
"Typing":["Do you type a lot every day?","Are you good at typing quickly?","Do you prefer typing or writing by hand?"],
"Hobby":["What hobbies do you have?","How much time do you spend on your hobbies?","Did you have different hobbies as a child?"],
"Sports team":["Do you support any sports team?","Did you follow sports teams when you were younger?","Why do people become loyal to a sports team?"],
"Reading":["Do you enjoy reading?","What kind of things do you usually read?","Do you read more or less than you did in the past?"],
"Gifts":["Do you like giving gifts to other people?","What kind of gifts do you usually give?","What is a memorable gift you have received?"],
"Morning time":["What do you usually do in the morning?","Do you prefer getting up early or late?","Are your mornings different at weekends?"],
"Walking":["Do you walk a lot in your daily life?","Where do you usually go for a walk?","Did you walk more when you were younger?"],
"Food":["What kind of food do you like?","Do you prefer eating at home or outside?","Is there any food you disliked as a child but like now?"],
"Pets and Animals":["Do you like animals?","Did you have a pet when you were a child?","What animals are popular as pets in your country?"],
"The city you live in":["What do you like about the city you live in?","Is there anything you would like to change about your city?","Do you think you will continue living there in the future?"],
"Home/Accommodation":["Do you live in a house or an apartment?","What is your favourite room at home?","What would you like to change about your home?"],
"Hometown":["Where is your hometown?","What do you like most about your hometown?","Has your hometown changed much in recent years?"],
"The area you live in":["What is the area where you live like?","What do you like about your neighbourhood?","Is it a good place for young people?"],
"Work/studies":["Do you work or are you a student?","What do you like about your work or studies?","Is there anything you would like to change about it?"],
"Films/cinemas":["Do you enjoy watching films?","How often do you go to the cinema?","Do you prefer watching films at home or at a cinema?"],
"Evening time":["What do you usually do in the evening?","Do you prefer busy or quiet evenings?","Are your evenings different at weekends?"],
"Sports programs":["Do you watch sports programmes?","What kinds of sports do you like watching?","Did you watch more sports programmes when you were younger?"]
};
const P1_TOPICS=Object.keys(P1Q);

function cue(theme){
  const sets={
    person:["who this person is","how you know this person","what this person did","and explain why this person is memorable to you"],
    place:["where it is","when you went there or first knew about it","what you did or can do there","and explain why this place is memorable to you"],
    tech:["what it was","when it happened","what you did about it","and explain how you felt about the experience"],
    work:["what the job, company or activity is","how you knew about it","what people do there","and explain why it interests you"],
    law:["what the law is","why it is needed","who it would affect","and explain what difference it could make"],
    object:["what it is","when you got or used it","how you use it or what happened","and explain why it is important or memorable to you"],
    media:["what it was","when you saw, watched or read it","what it was about","and explain why you remember it"],
    sport:["what the event was","when and where you watched it","who you watched it with","and explain how you felt about it"],
    nature:["what it is","where it is or where you learned about it","what you know about it","and explain why it interests you"],
    food:["what the food or meal was","when and where you had it","who you were with","and explain why it was special"],
    learning:["what you learned or wanted to learn","when you started","how you learned it","and explain why it was important to you"],
    experience:["when and where it happened","who was involved","what happened","and explain how you felt about it"]
  };return sets[theme]||sets.experience
}

const RAW_P2=[
["保护环境的法律","Describe a law in your country that helps protect the environment","law"],
["克服困难成功的人","Describe a person who met difficulties but succeeded","person"],
["改变重要想法","Describe a time when you changed an important opinion of yours","experience"],
["想颁布的环保法律","Describe an environmental law you would like to introduce","law"],
["别人帮助解决问题","Describe a time when a person did something to help you solve a problem","experience"],
["包含动物的故事或书","Describe a story or book with animals in it","media"],
["喜欢拜访但不想住的家","Describe a home that you like to visit but do not want to live in","place"],
["最近看过的电视/网络节目","Describe a TV show or online program you have watched recently","media"],
["推荐旅行过的地方","Describe a place you have travelled to and would recommend","place"],
["遇到的科技问题","Describe a challenging technological problem you faced","tech"],
["长时间未收到回复","Describe a time when you sent a message but received no reply for a long time","experience"],
["擅长学习和说语言的人","Describe a person who is good at learning and speaking new languages","person"],
["重要决定","Describe an important decision that you made","experience"],
["电子产品故障","Describe a time when you had a problem with using an electronic device","tech"],
["当地新闻","Describe a piece of local news you have heard or seen","media"],
["名人广告","Describe an advertisement with a famous person in it","media"],
["看过的现场比赛","Describe a live sports event you watched","sport"],
["特殊场合下吃的食物","Describe some food you ate on a special occasion","food"],
["长期追求/目标","Describe a long-term goal or ambition you would like to achieve","experience"],
["在团队中工作","Describe a time when you worked in a group","experience"],
["近期改变的计划","Describe a plan that you had to change recently","experience"],
["商业上很成功的人","Describe a person you know who has a successful business","person"],
["想从事医疗行业的人","Describe a person you know who would like to choose a career in the medical field","person"],
["想颁布的新法律","Describe a new law you would like to introduce in your country","law"],
["喜欢在家/花园种菜的人","Describe a person who loves to grow vegetables at home or in the garden","person"],
["发小","Describe your best friend","person"],
["无聊的地方","Describe a place you went to that was boring","place"],
["早起经历","Describe a time when you got up early","experience"],
["有趣视频","Describe an interesting video you have watched","media"],
["喜欢或不喜欢的高建筑","Describe a tall building you like or dislike","place"],
["安静的地方","Describe a quiet place you like to go to","place"],
["去过且喜欢的城市","Describe a city you have visited and liked","place"],
["爱护自然的人","Describe a person who likes to look after the natural world","person"],
["想从事的短期海外工作","Describe a short-term job you want to have in a foreign country","work"],
["鼓励别人做不愿做的事","Describe a time when you encouraged someone to do something they did not want to do","experience"],
["乐于助人的人","Describe a person who often helps others","person"],
["花费超过预期的物品","Describe an item on which you spent more than expected","object"],
["发挥想象力","Describe a time you needed to use your imagination","experience"],
["有趣的建筑","Describe an interesting building you have seen","place"],
["朋友自学","Describe one of your friends who learned something without a teacher","person"],
["近期观影","Describe a movie you watched and enjoyed recently","media"],
["不享受的音乐活动","Describe a music event that you did not enjoy","media"],
["机智解决问题的人","Describe a person who solved a problem in a smart way","person"],
["购物场所","Describe a shopping place you enjoy visiting","place"],
["自行车/摩托车/汽车旅行","Describe a bicycle, motorcycle or car trip you would like to take","place"],
["想拥有的科技产品","Describe a piece of technology, not a phone, that you would like to own","object"],
["Apps/程序","Describe a program or app on your computer or phone","tech"],
["擅长做计划的人","Describe a person who is good at making plans","person"],
["喜欢画画的孩子","Describe a child who likes drawing or painting","person"],
["给别人建议","Describe a time when you gave advice to others","experience"],
["为家人骄傲","Describe a time when you felt proud of a family member","experience"],
["微笑的场合","Describe an occasion when many people were smiling","experience"],
["禁止用手机的场合","Describe an occasion when you were not allowed to use your mobile phone","experience"],
["想见的名人","Describe a famous person you would like to meet","person"],
["完美工作","Describe a perfect job you would like to have in the future","work"],
["想有空时去旅游的地方","Describe a place you would like to visit in your free time","place"],
["收到特殊蛋糕","Describe a special cake you received from others","food"],
["在成功公司工作的人","Describe a person who works in a successful company","person"],
["语言学习","Describe a language you would like to learn","learning"],
["重要河流/湖泊","Describe an important river or lake in your country","nature"],
["花费甚少的外出日","Describe a day out when you spent very little money","experience"],
["组织快乐活动","Describe a time when you organized a happy event successfully","experience"],
["交通拥堵","Describe a time when you were stuck in a traffic jam for a very long time","experience"]
];
const P2_CARDS=RAW_P2.map(([source,q,theme])=>({source,q,theme,cues:cue(theme)}));

const P3={
person:["What qualities make someone easy to admire?","Do people today have more role models than in the past?","Why are some people more willing to help others?","Can people learn important qualities from friends and family?","Do famous people have too much influence on young people?"],
place:["Why do people enjoy visiting new places?","What makes a city comfortable to live in?","How can tourism change a local area?","Do people care more about the appearance of buildings now?","Do you think people will travel differently in the future?"],
tech:["Why do people depend so much on technology today?","What kinds of technology cause problems for older people?","Should schools teach children how to solve simple technology problems?","Do you think technology makes people more independent or less independent?","How can people avoid wasting too much time on apps?"],
work:["What makes a job attractive to young people today?","Why do some people change careers several times?","What qualities are important for running a successful business?","Do people care more about salary or job satisfaction?","Do you think people will work more internationally in the future?"],
law:["Why do governments need laws to change people's behaviour?","What makes a law effective?","Should environmental rules be stricter?","Why do some people ignore rules even when they understand them?","Should children learn more about laws at school?"],
media:["Why do people have different tastes in entertainment?","How has the internet changed the way people discover entertainment?","Should artistic activities be taught more seriously at school?","Why can famous people influence what consumers buy?","Do short videos have a positive or negative influence on people?"],
sport:["Why do people enjoy watching live sports?","What are the benefits of team sports for children?","Why do some sports attract much larger audiences than others?","Should governments spend money on major sporting events?","Is watching sport as valuable as doing sport?"],
nature:["Why is it difficult to persuade people to protect nature?","Should governments use laws to change people's environmental behaviour?","What environmental problems are most visible in cities?","Why are rivers and lakes important to a country?","Do individuals or large organisations make a bigger environmental difference?"],
food:["Why is food important during festivals and celebrations?","Do traditional foods become less popular with younger people?","Why do people enjoy sharing food with others?","How has eating out changed in recent years?","Should children learn how to cook?"],
learning:["Why do adults decide to learn new languages?","Is it easier for children to learn languages than adults?","How has technology changed language learning?","Should everyone learn a second language?","What makes someone a successful independent learner?"],
object:["Why do people sometimes spend more than they planned?","How do advertisements affect what people buy?","Why do people replace electronic products so often?","Do people value useful objects more than beautiful ones?","How can consumers make better buying decisions?"],
experience:["Why do some people find it easier to deal with problems than others?","Do people learn more from success or from failure?","How important is advice when people make decisions?","Why do plans sometimes change unexpectedly?","Do young people take more risks than older people?"]
};