(()=>{
const groups=window.P2_2026Q4_GROUPS||[];
const byQ={};for(const g of groups)for(const t of g.topics)byQ[t.q]=t;
const add=(q,i,text)=>{const t=byQ[q];if(t?.reviewed?.[i])t.reviewed[i].text+=" "+text};
add("Q03",1,"My friend was only free that afternoon, so we could not simply come back at a quieter time.");
add("Q04",1,"She sometimes takes photos of museum pieces so she can compare the details again in her studio.");
add("Q08",1,"I would make the fee higher during the busiest times and lower when traffic is lighter.");
add("Q10",0,"The story also mentioned that the market would be open to the public the following weekend.");
add("Q12",2,"She is especially interested in children because she likes explaining things in a calm and simple way.");
add("Q13",1,"There was no special event that day, so the closed areas were even more noticeable.");
add("Q19",1,"She prefers natural light and usually takes several versions before choosing the one she likes.");
add("Q21",0,"I first heard about similar congestion charges while reading about traffic policies used in large cities.");
add("Q21",1,"Emergency vehicles and people with special needs could have exemptions, so the rule would not affect everyone in the same way.");
add("Q22",2,"I also like that neither character solves everything alone; they need each other's different strengths.");
add("Q24",0,"The video appeared on social media a few weeks before the festival, so it felt timely rather than random.");
add("Q25",1,"Our other friend kept the confirmation messages and meeting times together so we did not lose important information.");
add("Q26",1,"Emergency vehicles and some essential workers could be exempt, which would make the rule more practical.");
add("Q35",2,"The living area and storage are close together, so even a few extra boxes make the space feel full.");
add("Q36",1,"She also repeats short clips aloud when she hears an expression that sounds useful.");
add("Q38",1,"We told our boss early enough to reorganise the urgent work before the weekend.");
add("Q40",0,"I found it while scrolling through social media, and the bright colours made me stop.");
add("Q41",0,"I watched it on YouTube with subtitles, which made the longer answers easier to follow.");
add("Q43",2,"She also avoids comparing every free hour with work, so she does not feel guilty about taking breaks.");
add("Q44",2,"During the trip, she used maps on her phone and sent us a message after she reached the hotel.");
add("Q46",2,"We could also stop for photos whenever we wanted instead of waiting for the next station.");
add("Q48",2,"I also checked with my manager first so the change would not create a problem for the rest of the team.");
add("Q49",1,"We even used slightly different patterns, so the finished mooncakes were easy to tell apart.");
add("Q50",2,"She also spends a lot of time communicating with artists and promoting new work, so the business depends on more than the technology.");
add("Q51",1,"She used to draw in the margins of her notebooks, and I would often sit beside her and watch.");
add("Q52",2,"The food court is convenient, but convenience alone is not enough to make me want to stay for hours.");
})();
